[project]
name = "code-explainer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-cloud-aiplatform>=1.148.1",
    "google-generativeai>=0.8.6",
    "ipython>=9.6.0",
    "mistune>=3.1.4",
    "openai>=2.2.0",
    "requests>=2.32.5",
    "rich>=13.9.4",
    "streamlit>=1.56.0",
    "toyaikit",
    "watchdog>=6.0.0",
]

[tool.uv.sources]
toyaikit = { path = "../toyaikit", editable = true }

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]

#[tool.uv.sources]
#toyaikit = { path = "../toyaikit", editable = true }
